// Regenerates .github/copilot-instructions.md from harness sources:
// static project context + team memory + the project-index map.
// Run: bun .harness/scripts/sync-copilot.ts   (or: npm run harness:sync-copilot)
import { readFileSync, writeFileSync, mkdirSync, existsSync } from "node:fs";
import { join } from "node:path";

const root = join(import.meta.dir ?? __dirname, "..", "..");

function readOr(path: string, fallback: string): string {
  return existsSync(path) ? readFileSync(path, "utf8") : fallback;
}

// Strip the budget header comment and --- separators from team memory.
const teamRaw = readOr(join(root, ".harness/team-memories/team.md"), "");
const teamEntries = teamRaw
  .replace(/<!--[\s\S]*?-->/g, "")
  .split(/^---$/m)
  .map((e) => e.trim())
  .filter(Boolean);

const indexMap = readOr(join(root, ".harness/project-index/index.md"), "")
  .split("\n")
  .filter((l) => l.startsWith("- "))
  .join("\n");

const out = `<!-- GENERATED by .harness/scripts/sync-copilot.ts — do not edit by hand.
     Sources: .harness/team-memories/team.md, .harness/project-index/index.md -->

# intelligents — Copilot instructions

## What this project is

A VS Code extension in TypeScript: an "agentic CRM" that manages persistent AI
coding agents — create, view, and edit agents and their skills — integrating
with Claude Code (terminal sessions) and GitHub Copilot.

## Stack & conventions

- TypeScript, esbuild bundle to \`dist/extension.js\`; \`vscode\` is the only external.
- Domain logic under \`src/\` must not import \`vscode\` — keep it host-free and testable.
- Conventional Commits (\`feat:\`, \`fix:\`, \`chore:\`…) — enforced by commitlint.
- Webviews: strict CSP, nonce'd scripts, validated \`postMessage\` payloads,
  \`--vscode-*\` CSS variables only.
- Agent/skill files on disk (\`.claude/agents\`, \`.claude/skills\`, \`~/.claude\`) are
  the data store: parse frontmatter defensively, preserve unknown keys, never delete.

## Things to avoid

- Do not push to main, publish, or add dependencies without asking.
- No \`*\` activation events; no blocking I/O in \`activate\`.
- Never edit this file directly — change the harness sources and re-run the sync.

## Team knowledge

${teamEntries.length ? teamEntries.map((e) => e.replace(/^- ?/, "- ")).join("\n") : "_(none recorded yet)_"}

## Codebase map

${indexMap || "_(project not yet indexed — run /index in Claude Code)_"}
`;

mkdirSync(join(root, ".github"), { recursive: true });
writeFileSync(join(root, ".github/copilot-instructions.md"), out);
console.log("wrote .github/copilot-instructions.md");
