import { existsSync } from "node:fs";
import { mkdir, readFile, unlink, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { parseDocument } from "../frontmatter";
import type { ToolAdapter } from "./adapters";
import { listMdNames, readText } from "./fsUtil";

const GENERATED_BANNER =
  "<!-- GENERATED by harness — do not edit. Source of truth: .harness/ -->";

export interface StubResult {
  path: string;
  action: "written" | "skipped (no change)";
}

function quoteYaml(value: string): string {
  return `"${value.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;
}

export async function buildAgentStubContent(
  root: string,
  adapter: ToolAdapter,
  agentName: string,
): Promise<string | null> {
  const sourcePath = join(root, ".harness", "agents", `${agentName}.md`);
  if (!existsSync(sourcePath)) {
    return null;
  }
  const source = await readText(sourcePath);
  const { frontmatter } = parseDocument(source);

  const description = frontmatter.description ?? "";
  const model = frontmatter.model ?? "inherit";
  const skills = (frontmatter.skills ?? "")
    .split(",")
    .map((s) => s.trim())
    .filter(Boolean);

  const skillsLine =
    skills.length > 0 && adapter.supportsAgentSkills
      ? `\nskills: ${skills.join(", ")}`
      : "";
  const skillsMention =
    skills.length > 0 && !adapter.supportsAgentSkills
      ? `\nBefore starting, read and apply these skills: ${skills
          .map((s) => `${s} (${adapter.skillsDir}/${s}/SKILL.md)`)
          .join(", ")}.\n`
      : "";

  const protocolPath = join(root, ".harness", "protocol", "memory-protocol.md");
  const obeyLine = existsSync(protocolPath)
    ? "\nAlways obey @.harness/protocol/memory-protocol.md\n"
    : "\n";

  return `---
name: ${agentName}
description: ${quoteYaml(description)}
model: ${model}${skillsLine}
---
${GENERATED_BANNER}
Follow the full agent definition at @.harness/agents/${agentName}.md${skillsMention}${obeyLine}`;
}

export async function generateAgentStub(
  root: string,
  adapter: ToolAdapter,
  agentName: string,
): Promise<StubResult | null> {
  const stub = await buildAgentStubContent(root, adapter, agentName);
  if (stub === null) {
    return null;
  }

  const outDir = join(root, adapter.agentsDir);
  await mkdir(outDir, { recursive: true });
  const outPath = join(outDir, `${agentName}.md`);

  const existing = existsSync(outPath) ? await readText(outPath) : null;
  if (existing === stub) {
    return { path: outPath, action: "skipped (no change)" };
  }
  await writeFile(outPath, stub, "utf8");
  return { path: outPath, action: "written" };
}

export async function buildCommandStubContent(
  root: string,
  commandName: string,
): Promise<string | null> {
  const sourcePath = join(root, ".harness", "commands", `${commandName}.md`);
  if (!existsSync(sourcePath)) {
    return null;
  }
  const source = await readText(sourcePath);
  const { frontmatter } = parseDocument(source);

  const description = frontmatter.description ?? "";
  const argHintLine = frontmatter["argument-hint"]
    ? `\nargument-hint: ${frontmatter["argument-hint"]}`
    : "";

  return `---
description: ${description}${argHintLine}
disable-model-invocation: true
---
${GENERATED_BANNER}
Execute the command defined at @.harness/commands/${commandName}.md
`;
}

export async function generateCommandStub(
  root: string,
  adapter: ToolAdapter,
  commandName: string,
): Promise<StubResult | null> {
  const stub = await buildCommandStubContent(root, commandName);
  if (stub === null) {
    return null;
  }

  const outDir = join(root, adapter.commandsDir);
  await mkdir(outDir, { recursive: true });
  const outPath = join(outDir, `${commandName}.md`);

  const existing = existsSync(outPath) ? await readText(outPath) : null;
  if (existing === stub) {
    return { path: outPath, action: "skipped (no change)" };
  }
  await writeFile(outPath, stub, "utf8");
  return { path: outPath, action: "written" };
}

async function deleteGeneratedStub(path: string): Promise<boolean> {
  if (!existsSync(path)) {
    return false;
  }
  const content = await readText(path);
  if (!content.includes("GENERATED by harness")) {
    return false;
  }
  await unlink(path);
  return true;
}

export async function deleteAgentStub(
  root: string,
  adapter: ToolAdapter,
  agentName: string,
): Promise<boolean> {
  return deleteGeneratedStub(join(root, adapter.agentsDir, `${agentName}.md`));
}

export async function deleteCommandStub(
  root: string,
  adapter: ToolAdapter,
  commandName: string,
): Promise<boolean> {
  return deleteGeneratedStub(
    join(root, adapter.commandsDir, `${commandName}.md`),
  );
}

export async function listCommandNames(root: string): Promise<string[]> {
  return listMdNames(join(root, ".harness", "commands"));
}

export async function listAgentSourceNames(root: string): Promise<string[]> {
  return listMdNames(join(root, ".harness", "agents"));
}

export async function bannerStubNames(
  root: string,
  dir: string,
): Promise<string[]> {
  const abs = join(root, dir);
  if (!existsSync(abs)) {
    return [];
  }
  const names = await listMdNames(abs);
  const out: string[] = [];
  for (const name of names) {
    const content = await readText(join(abs, `${name}.md`));
    if (content.includes("GENERATED by harness")) {
      out.push(name);
    }
  }
  return out;
}
